stages:
  preprocessing:
    cmd: python3 src/preprocessing.py -p data/recipes.csv
    deps:
    - data/recipes.csv
    - src/preprocessing.py
    outs:
    - data/prepared
  modeling:
    cmd: python3 src/modeling.py -p data/prepared/docs.pkl
    deps:
    - data/prepared/docs.pkl
    - src/modeling.py
    params:
    - modeling.num_topics
    outs:
    - data/model
  predict:
    cmd: python3 src/predict.py -m data/model/model.pkl -p data/model/corpus.pkl
    deps:
    - data/model/corpus.pkl
    - data/model/model.pkl
    - src/predict.py
    outs:
    - data/predictions
  evaluate:
    cmd: python3 src/evaluate.py -m data/model/model.pkl -p data/prepared/docs.pkl
      -c data/model/corpus.pkl -d data/model/dictionary.pkl
    deps:
    - data/model/corpus.pkl
    - data/model/dictionary.pkl
    - data/model/model.pkl
    - data/prepared/docs.pkl
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - visualization.html:
        cache: false
